### ISSUE TITLE
Needs LICENSE

### ISSUE THREAD

**Issue by coolaj86** [jonatkins/s2-geometry-javascript#5]
Which license do you prefer? I'll add it and PR.
- MIT
- BSD 2-clause
- BSD 3-clause
- Apache-2.0
- ISC

I like to dual-license Apache-2.0 and MIT because then it can be GPL-compatible via MIT and also grant relevant rights in perpetuity all IP via Apache-2.0.

**Comment by jonatkins** [comment]
ISC license
